# serivce name
spring: 
  application: 
    name: company-service
    
server: 
  port: 8001

# eureka server url
eureka: 
  client: 
    service-url:
      default-zone: http://localhost:8761/eureka